### ISSUE TITLE
No such file or directory: 'autopep8'

### ISSUE THREAD

**Issue by medyagh** [Leo-G/Flask-Scaffold#26]
```python3.5 scaffold.py scaffold/blog.yaml
app/authors created successfully
Registered Blueprints for  authors
Updated app/templates/static/js/app.js
Updated app/templates/index.html
Updated app/templates/index.html
Updated tests.bash
Updated conf.js
Traceback (most recent call last):
  File "scaffold.py", line 407, in <module>
    run_autopep8()
  File "scaffold.py", line 168, in run_autopep8
    ['autopep8', '--in-place', '--recursive', 'app'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'autopep8'```

**Comment by Leo-G** [comment]
The code seems to have generated fine, so you should be able to use it.

I am not sure if this is due autopep8 not being installed on OSX, can you do a "pip list" and see if it is already installed?

**Comment by mgd722** [comment]
I've encountered the same issue, OS X 10.11.4 running Python 3.5 in a virtual environment.  It's definitely installed in my virtual environment (`pip list` there confirms this).

**Comment by Leo-G** [comment]
@mgd722 Thanks for the alternative fix, will need to some more testing to get to the bottom of this
