### ISSUE TITLE
ValueError: flask-restful blueprints can only be registered once.

### ISSUE THREAD

**Issue by codalprashant** [Leo-G/Flask-Scaffold#30]
python db.py db init
Traceback (most recent call last):
  File "db.py", line 4, in <module>
    from run import app
  File "/home/codal/pythonlearning/flaskpro/run.py", line 4, in <module>
    app = create_app('config')
  File "/home/codal/pythonlearning/flaskpro/app/__init__.py", line 50, in create_app
    app.register_blueprint(authors, url_prefix='/api/v1/authors')
  File "/home/codal/pythonlearning/fnev/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/codal/pythonlearning/fnev/local/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/home/codal/pythonlearning/fnev/local/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/home/codal/pythonlearning/fnev/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 184, in _deferred_blueprint_init
    raise ValueError('flask-restful blueprints can only be registered once.')
ValueError: flask-restful blueprints can only be registered once.

**Comment by Leo-G** [comment]
You have authors blueprint registered twice, remove the below line from /home/codal/pythonlearning/flaskpro/app/init.py 

      from app.authors.views import authors
      app.register_blueprint(authors, url_prefix='/api/v1/authors')
